jedcn/reveal-ck

features/emoji.feature, lib/reveal-ck/markdown.rb, lib/reveal-ck/markdown/post_processor.rb, lib/reveal-ck/markdown/pre_processor.rb, spec/lib/reveal-ck/commands/serve_spec.rb, spec/lib/reveal-ck/markdown/post_processor_spec.rb, spec/lib/reveal-ck/markdown/pre_processor_spec.rb, spec/lib/reveal-ck/markdown/slide_markdown_template_spec.rb
These changes fix issue #29.
reveal-ck has two classes `PreProcessor` and `PostProcessor` that work before and after its embedded markdown processor runs.
This changes makes it so that the `PreProcessor` turns something like `:money_with_wings:` into `:moneyEUwithEUwings:` (where `EU` is a token that stands for `E`moji `U`nderscore, and, more importantly, isn't modified by the markdown processor).
Then the `PostProcessor` does the reverse.
This allows the emoji to reach the next stage of processing-- which is when `RevealCKEmojiFilter` transforms the `:money_with_wings:` into :money_with_wings:
This one's for us, @banderson.
=> Enhanced support for emojis

lib/reveal-ck/markdown/slide_markdown.rb, spec/lib/reveal-ck/markdown/slide_markdown_template_spec.rb
Hi,
I wrote a slides.md that contains the following REPL output:
```clojure
user=> (atom 10)
#<Atom@6cbda790: 10>
```
Then generating HTML slides results in:
user=> (atom 10)
#<atom>
</atom>
That is, `<Atom@6cbda790: 10>` in my slides.md happens to be interpreted as an HTML tag.
I just want my original code block to be shown in browsers as is.
In this pull request I simply escape special characters in code blocks so that they won't be interpreted as tags.
Thanks in advance!
=> HTML-escape special characters in code blocks

lib/reveal-ck/commands/listen_to_rebuild_slides.rb, lib/reveal-ck/commands/print_banner.rb, lib/reveal-ck/commands/start_web_server.rb, lib/reveal-ck/commands/thread_waker.rb, lib/reveal-ck/presentation.rb, lib/reveal-ck/presentation_dsl.rb, lib/reveal-ck/templates/processor.rb, spec/.rubocop.yml, spec/lib/reveal-ck/commands/listen_to_rebuild_slides_spec.rb, spec/lib/reveal-ck/templates/processor_spec.rb
This pull request contains changes that update reveal-ck so that it conforms to the preferences of the latest rubocop release.
reveal-ck will use the latest rubocop available, and so, as new versions of rubocop are published reveal-ck falls behind.
The changes in this pull request make it so that the code should pass with the latest rubocop.
=> [rubocop] Update code to pass latest rubocop preferences

features/generate-with-config.feature, files/reveal-ck/templates/index.html/head.html.erb, lib/reveal-ck/config.rb, spec/lib/reveal-ck/builders/index_html_spec.rb, spec/lib/reveal-ck/config_spec.rb
This pull request is the same thing as https://github.com/jedcn/reveal-ck/pull/39, but it adds a cucumber/aruba feature that builds out a slide deck when you run the tests, and verifies that the slide deck contains the expected HTML.
=> Add "description" and "generator" meta tags

spec/lib/reveal-ck/builders/index_html_spec.rb
I noticed the tests were complaining that `VERSION` was redefined
=> Remove warning that VERSION is redefined

features/generate-with-config.feature, lib/reveal-ck/builders/create_slides_html.rb, lib/reveal-ck/config.rb, spec/lib/reveal-ck/builders/create_slides_html_spec.rb
I like the rake task and will keep iterating on it.
I feel the filter in `config.yml` is more useful if a user can also say 'here is where you can find these filters'
This allows you to add a require block in the config to do that
(the rake task broke down when I wanted to serve up the assets. so I still need this, bundler, or `init.rb`
=> Allow config file to specify requires for filters

.rubocop.yml, spec/spec_helper.rb
3 small things.
1. rubocop was running on reveal.js files.
This made my build blowup locally
This removes that. (but added a deprecation warning that I can't figure out)
2. It was complaining that Rakefile was a deprecated pattern
This fixes that.
3. Tilt was complaining that requiring erb and haml are not thread safe.
This adds them to the `spec_helper.rb`
For this same reason, I have a `require: 'tilt/erb'` in my local `config.yml` file.
Thanks
--K
=> Silence rubocops

ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md
Github recently allowed people to supply templates for pull requests and issues: https://github.com/blog/2111-issue-and-pull-request-templates.
And this PR does just that.
=> Create PR and Issue Templates

lib/reveal-ck/builders/copy_files_task.rb, spec/lib/reveal-ck/builders/copy_files_task_spec.rb
Yay. presentation time again... :)
Thanks for the great tool
Escape the slide directory name so it doesnt cause errors with regular expression matches.
This was blowing up with a slide deck called `n+1`
Only concern is there are other places in the code that don't properly escape
user input (e.g.: guard). but that is beyond the scope of this pr.
It now works for my directory and I added a spec.
If you prefer just changing the original spec's source directory name or a different approach, just give out a shout.
=> Build for directories with special characters

CHANGELOG.md, features/generate-with-markdown.feature, lib/reveal-ck/markdown/slide_markdown.rb
This change makes it so that you can write your notes in markdown. See the associate `.feature` file change for an example.
It's motivated in response to #68.
I wrote a failing feature first, and then I made the feature pass. I haven't done much more than that.
=> Support Markdown in notes

CHANGELOG.md, bin/reveal-ck, features/serve.feature, features/step_definitions/serve_steps.rb, lib/reveal-ck/commands/print_banner.rb, lib/reveal-ck/commands/serve.rb, lib/reveal-ck/commands/start_web_server.rb, spec/lib/reveal-ck/commands/print_banner_spec.rb, spec/lib/reveal-ck/commands/serve_spec.rb, spec/lib/reveal-ck/commands/start_web_server_spec.rb
This PR is based on #79.
It re-uses @scornelissen85 initial commit and adds two more administrative ones.
You can now supply a `--host` when starting up `reveal-ck serve`.
=> Specify host

.rubocop.yml, CHANGELOG.md, Rakefile, bin/reveal-ck, examples/programmatic_slides.rb, features/generate-with-config.feature, files/reveal-ck/Guardfile, files/reveal-ck/templates/index.html/head.html.erb, files/reveal-ck/templates/index.html/index.html.erb, lib/reveal-ck/builders/create_index_html.rb, lib/reveal-ck/builders/index_html.rb, lib/reveal-ck/config.rb, lib/reveal-ck/presentation.rb, rakelib/ci.rake, reveal-ck.gemspec, spec/lib/reveal-ck/builders/create_slides_html_spec.rb, spec/lib/reveal-ck/builders/creation_task_spec.rb, spec/lib/reveal-ck/builders/index_html_spec.rb, spec/lib/reveal-ck/config_spec.rb, spec/lib/reveal-ck/markdown/post_processor_spec.rb, spec/lib/reveal-ck/markdown/pre_processor_spec.rb, spec/lib/reveal-ck/markdown/slide_markdown_template_spec.rb, spec/spec_helper.rb
This change builds off of #82.
In addition to the work there it:
* Does some house keeping around rubocop and `CHANGELOG.md`.
* Makes the `<head prefix=""/>` configurable
However, the value of `<head prefix=""/>` defaults to what's needed to support http://ogp.me/.
I'm opening this PR to provide transparency to @sue445.
The changes in #82 will be active once this comes in.
Thanks for your contribution!
=> Supporting meta names and properties

features/generate-with-config.feature, files/reveal-ck/templates/index.html/head.html.erb, files/reveal-ck/templates/index.html/index.html.erb, lib/reveal-ck/config.rb, reveal-ck.gemspec
Supports OGP meta tag contents (e.g. `<meta property="og:title" >`)
I want to share URL of slide generated with `reveal-ck` to twitter or facebook, but content is very cheep :persevere:
This PR supports arbitrary embed meta tag.
https://sue445.github.io/reveal-ck-example/#/
```yaml
meta_properties:
og:type: "website"
og:title: "Example slide"
og:description: "Example slide"
og:url: "https://sue445.github.io/reveal-ck-example/#/"
og:image: "https://sue445.github.io/reveal-ck-example/images/github_unicorn.png"
meta_names:
twitter:card: "summary"
twitter:site: "@sue445"
twitter:creator: "@sue445"
twitter:title: "Example slide"
twitter:description: "Example slide"
twitter:image: "https://sue445.github.io/reveal-ck-example/images/github_unicorn.png"
```
=> Supports OGP meta tag contents

CHANGELOG.md, features/generate-with-js-plugin.feature, features/generate-with-js.feature, files/reveal-ck/templates/index.html/body.html.erb, files/reveal-ck/templates/index.html/script.js.erb, lib/reveal-ck/config.rb, lib/reveal-ck/render.rb, lib/reveal-ck/render/js_files.rb, lib/reveal-ck/render/plugin_files.rb, lib/reveal-ck/render/scope.rb
This PR starts with a commit from @jdoconnor.
It then builds on that commit to provide support for using reveal.js plugins.
I don't have much experience with plugins, and this work is based on what it takes to get a mermaid js plugin working.
This is what it does:
1. Presently, files put in the `js/` directory are copied into generated presentations. This PR includes a change that will add these files each into `<script />` tag.
2. Presently, files put in the `plugin/` directory are copied into generated presentations. This PR includes a change that will add the javascript files in the plugin directory to be added as dependencies in `baseOptions.dependencies`.
=> Support Plugins

files/reveal-ck/templates/index.html/script.js.erb, lib/reveal-ck/config.rb
Allow the config to support a list of dynamic dependencies for the js dependencies (needed to use plugins)
No testing done yet. If this is a feature that you'd like to see, I'm happy to add some tests. It looks like adding plugins into the presentation is already supported, but I didn't see a way to include them in the js context.
Example config
```yaml
title:      "some presentation"
author:     "Jay OConnor"
theme:      "sky"
js_dependencies:
- src: 'plugin/mermaid/mermaid.js'
```
=> dynamic js dependencies

.rubocop.yml, bin/reveal-ck, features/help.feature
Extend some logic used in `reveal-ck generate` to also be included in `reveal-ck serve`.
This fixes #80.
Added a feature to catch this in the future.
Verified that it failed and then passed.
=> Standardize what happens when slides file is missing

rakelib/prepare_release.rake
When you want to build a new release, you type:
rake prep_release NEW_VERSION=3.8.1
But if you haven't done this in awhile (😃) you might forget to supply `NEW_VERSION` as an environment variable.
This change makes it so that `rake prep_release` will stop unless this is present.
=> Enforce presence of NEW_VERSION

CHANGELOG.md, files/reveal-ck/templates/reload_Guardfile/Guardfile.erb, lib/reveal-ck/commands/listen_to_rebuild_slides.rb, lib/reveal-ck/commands/listen_to_reload_browser.rb, lib/reveal-ck/commands/serve.rb, spec/lib/reveal-ck/commands/listen_to_rebuild_slides_spec.rb, spec/lib/reveal-ck/commands/listen_to_reload_browser_spec.rb
This change is being suggested to address #98 and #99.
Previously, when running `reveal-ck serve`, the software always assumed the output directory (where slides were being created) was `slides/`.
This change now takes the implied output directory into account.
This is a work in progress. If it's not too much trouble, @agate-pris, please see if this change helps your situation.
I'm a bit pressed for time right now, but I'll take a closer look when I can. I still need to:
=> [WIP] Take output dir into account when running serve

CHANGELOG.md, features/emoji.feature, lib/reveal-ck/config.rb, spec/lib/reveal-ck/config_spec.rb
reveal-ck relies on github's hosting to reference emojis within slides.
Recently, github must have stopped supporting the paths they used to host emojis on-- they've switched to a new location.
That's just fine-- and I'm surprised it hasn't changed over the past four years-- so this PR supports the new URLs.
This is a fix for #101.
Thank you very much @justin-vanwinkle for reporting.
=> Fix emojis

.github/CONTRIBUTING.md
This PR updates a relative Markdown link in the CONTRIBUTING document. (Good document, by the way!) The link had broken.
- the file had moved and a relative link broke
=> Fix a path in a link in CONTRIBUTING
